/* USER MUTATIONS */
export const SET_USER = "SET_USER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_IS_ACTIVE = "SET_IS_ACTIVE";

/* PRODUCTS MUTATIONS */
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_FOR_YOU = "SET_PRODUCTS_FOR_YOU";

/* CATEGORIES MUTATIONS */
export const SET_CATEGORIES = "SET_CATEGORIES";

/* CART MUTATIONS */
export const SET_CART_DATA = "SET_CART_DATA";
export const SET_HAS_CART = "SET_HAS_CART";

/* SNACKBAR MUTATIONS */
export const SET_SNACKBAR = "SET_SNACKBAR";
